### ISSUE TITLE
Issues with closing too soon

### ISSUE THREAD

**Issue by LegzRwheelz** [fandangos/AutoHDR#2]
Hey man, I reached out to you on the Kodi forums with my idea and I truly appreciate you releasing this as a universal AutoHDR tool!!!! YOU ARE AWESOME!!!! I gotta tell you that this works Amazingly for Spider-Man (pun intended). 

**ISSUE**: 
AutoHDR doesn't wait long enough for God of War to open. It will switch HDR on then immediately switch it back off before GoW is even launched. I know I am launching correctly as I got Spider-Man to launch in HDR as expected.

**WHAT I HAVE TRIED**

- I am testing by editing my shortcuts and adding 
- I added a shortcut of AutoHDR_input to the "Send To..." menu (games launch fine, just not GoW)
`O:\AutoHDR_input.exe "F:\LaunchBox\Games\PC Games\SteamLibrary\steamapps\common\GodOfWar\GoW.exe"` 
in the "Target" field. I have also tested in CMD, creating a batch file and AutoHotKey.  
- I can activate HDR using the windows shortcut [WIN]Alt+B and launch the game just fine.
- I used your first release (with the 2 different executables) and wrote an AHK script that works great but I love this method so much more.

**MY THOUGHTS**
I have a feeling that GoW is launching a child process but I don't really know how to find out if it is or perhaps you can tell me how to figure out if the game is launching a child process so I can assist you in alleviating this issue for this as well as other games. When I go to task manager, I can see that along with GoW, Sony's crash handler app is launched. I moved the crash handler executable and tested again. No change. 

If you don't have GoW, I am willing to add you as a family member to my steam library with you if it will help in testing, just to get this to work with as many games as possible or perhaps you can tell me how to figure out if the game is launching a child process so I can assist you in alleviating this issue for this as well as other games. Maybe there's a way to make it wait a little bit longer before closing and turning off HDR? I was willing to learn C++ just to make this app for the rest of the community but since you already did this, maybe I can be your tester? I am willing to add you as a family member to my steam library with you if it will help in testing, just to get this to work with as many games as possible.

I am now thinking this issue is related to the steam window that opens as the game is loading (the little box with the progress bar showing cloud syncing of the save)

**SUGGESTIONS**
- check if HDR is already activated (via the hotkey I mentioned above), so it will still turn off when [whatever.exe] closes
- watch for child processes or go by PID at launch
- give the tool a longer window of waiting for the [whatever.exe] before closing the process
- make the console window invisible
- add "launch with AutoHDR" context menu entry
- run from system tray/notification panel, watching for [whatever1.exe], [whatever2.exe] that has been added to an ini
- add ini parsing to accompany the suggestion mentioned above

I know the last 2 are more a luxury than anything, it is just part of the initial idea I had. I would like to add that if AutoHDR_input.exe is placed in "..\Windows\System32" (like adding other added functions that are not native to Windows) effectively becomes a system function. Then it can be added to a shortcut's Target field like this:
`AutoHDR_input.exe "F:\LaunchBox\Games\PC Games\SteamLibrary\steamapps\common\GodOfWar\GoW.exe"`  and it just work It can also be called upon in AHK without the ".exe" part like:
`Run, AutoHDR_input` 
Perhaps there is a way of creating an installer that installs this directly and adds the context menu entry I mentioned above. 

**FINAL NOTE**
I am better at these little hacks and scripting than creating and compiling programs and I would really like to help in adding features that I have mentioned in this post. I would love to help you in any capacity with this amazing tool, man.

**Comment by fandangos** [comment]
If GoW stats a subprocess with a different name and closes the one while launching the game this method will not work because the parent process is done (and I don't think there's a wait to keep track of subprocess like that, specially if it's a completely different process and more so if it's some anti piracy measure).

I don't have much time to test per game solutions but...

I just pushed a slightly different version that you can find under AutoHDR_wait. 
This will launch whatever you want in HDR but only turn HDR off when a key is pressed within the console. 

Let me know if this solves the problem for you.

**Comment by fandangos** [comment]
By the way, I just downloaded GoW and tried with AutoHDR_input and it works as it should. 

But I'm not launching using steam or Launchbox

**Comment by LegzRwheelz** [comment]
> I just pushed a slightly different version that you can find under AutoHDR_wait. This will launch whatever you want in HDR but only turn HDR off when a key is pressed within the console.
 >
Hi, thanks for such a quick reply! This is so cool, I truly love your work. This is a great alternative, since I use LB and AHK, I could very easily close the process. Though it would remain on. I imagine an alternative is using ahk to send a key stroke. I'm wondering if there is a way to turn off HDR if the process is closed?
So as I suspected, steam is tripping up the tool. Steam loads the cloud save window, closes, then launches GoW. So is there a way to make the tool ignore Steam, Origin, EGS, LB etc. and just watch the PID or actual process name, rather than the exe that is launched?
I dont want to come across as needy, I really want to be part of coding this tool, I have zero exp. but am trying to learn. I honestly cannot figure out how to compile for the life of me, even watching tutorial videos. 😬

**Comment by fandangos** [comment]
I don't know exaclty what is going with those launchers but I'll explain how the code works:

Inside the exec function there's another one: `CreateProcess`, this will call whatever exe you add in front of AutoHDR_input.exe. 
If it's unable to launch it, it will error out (read the code from top to bottom). 
If it doesn't error out it will Create the Process, meaning it will call the exe and launch it. 

The `WaitForSingleObject` will halt the entire code while the process that was launched is running. 

When the process is killed it will close the handle of the process of the thread as per microsoft own code example I used.
It's not the script that is killing the game, it's something else or can be the user. 
Only then the HDR function is triggered and if HDR is ON it will turn it off, and if it's OFF will turn it on, since that's how the script works, it reverts the state of HDR.

So, if when you launch the game inside Steam and steam launches GoW.exe, kills it and launch it again, it's impossible for the script to get it. 
The only way I see of doing something like that would be grabbing the process title or information, store it and let a 5 second checker run but that's a terrible way to handle this. 
It's not bulletproof and it lags. 

So, as I see you already figured out by the e-mail you sent me, it's those launchers that are killing and relaunching the executable and besides a floating cmd window for the user to kill HDR manully I don't see any other way around this. 

Maybe adding the batch script to Steam as a game and using steam to launch it would be a easier solution but not 100% user friendly.

**Comment by LegzRwheelz** [comment]
I appreciate your explanation of how this works. I can handle above average
to semi-complicated tasks on Windows, I've created multiple scripts in AHK
and AutoIt as well as batch files. I can even read source code and somewhat
understand what is going on...Like I said, it's compiling that throws me. I
want to educate myself on your coding and add a bit more functionality,
namely checking the HDR state and then have it listen for the process id (I
believe that's what you called it). again, thank you so much for the
explanations and I'm gonna find some  crash course lessons.. of you don't
mind though, can you tell me how I can compile using VS 2022? I try to
debug but nothing happens, I try to compile, nothing happens. What am I
doing wrong? What am I supposed to be doing?

**Comment by fandangos** [comment]
It's probably outputting some errors and you are not catching it. 

Use the Kodi (xbmc) tutorial up to step 3:
https://github.com/xbmc/xbmc/blob/master/docs/README.Windows.md

It should get yourself ready to compile.
